name: .NET
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage"
    - name: Upload to Codecov
      uses: codecov/codecov-action@v3
  publish:
    runs-on: ubuntu-20.04
    needs: build
    if: ${{ github.event_name == 'push' }}
    steps:
    - uses: actions/checkout@v4
    - name: publish on version change
      id: publish_nuget
      uses: rohith/publish-nuget@v2
      with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: BervProject.Validation.Common/BervProject.Validation.Common.csproj
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
  docs:
    runs-on: ubuntu-20.04
    if: ${{ github.event_name == 'push' }}
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: mattnotmitt/doxygen-action@v1
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site/html/

